### ISSUE TITLE
Add php artisan down/up

### ISSUE THREAD

**Issue by tomzx** [eXolnet/laravel-envoy#10]
Add `php artisan down` at the beginning of the process (as late as possible) and `php artisan up` at the end.

The moment it would make the most sense is before running the migrations (currently `deploy:updated`) (down) and after the symlink (`deploy:symlink`) has for the current release has been setup (up).

**Comment by xel1045** [comment]
It possible when overwriting the `deploy:published` task:

```
@task('deploy:published')
    cd "{{ $releasePath }}"

    php artisan down
    
    //

    php artisan up
@endtask
```
