### ISSUE TITLE
Allow user to specify a port

### ISSUE THREAD

**Issue by martinblanchette** [eXolnet/laravel-envoy#24]

**Comment by tomzx** [comment]
Based on https://laracasts.com/forum/?p=939-problem-with-laravel-envoy/p1#p4358, you can add -p port# as part of the server string. A hack more than a real solution, I'll agree with that. I guess we could hide that fact by providing a _port_ key which would do the magic of doing $server.' -p '.$port in the back.

**Comment by xel1045** [comment]
Well, it might be the solution, but we quote the server informations:

```
@servers(['web' => '-A "'. $server .'"'])
```

It could be a good idea to add the port in the configuration and generate the proper connection string.

**Comment by tomzx** [comment]
@xel1045 So we're already using it in a hacky way too :)

**Comment by xel1045** [comment]
Sure! :yum:

**Comment by xel1045** [comment]
You can now specify it using the `ssh_options` configuration.
