### ISSUE TITLE
Replace git clone --depth 1 with a full git clone and git fetch subsequently

### ISSUE THREAD

**Issue by tomzx** [eXolnet/laravel-envoy#4]
The current method of updating the repository is possibly very inefficient as will it delete the existing repository folder and sync the whole repository at a specific point in time. Depending on the size of the repository at that time, this may result in many MB/GB of data being downloaded while a simple git fetch could have ended up downloading a very small delta.

A better repository syncing method would be to clone the whole repository and fetch changes on each subsequent update.

Here is some pseudo-code:

```
if (file_exists($repository) {
    git fetch
} else {
    git clone
}
 git checkout -f branch/sha1/tag
```

**Comment by xel1045** [comment]
I accept PRs :)
