### ISSUE TITLE
Add migrate task

### ISSUE THREAD

**Issue by tomzx** [eXolnet/laravel-envoy#6]
It appears that we had a `deploy:migrate` task at some point but it is not there anymore.

```
@task('deploy:migrate')
    cd "{{ $releasePath }}" && php artisan migrate
@endtask
```

Is there any reason that is gone @xel1045?

**Comment by xel1045** [comment]
Yes, since it's app dependant.

**Comment by tomzx** [comment]
I think the task should be available, but not included in the `deploy` macro, what do you think?

**Comment by xel1045** [comment]
Maybe, but how do you trigger it?

**Comment by xel1045** [comment]
It's possible when overwriting the `deploy:publish` task in your `Envoy.blade.php`:

```
@task('deploy:published')
    cd "{{ $releasePath }}"

    php artisan migrate --force
@endtask
```
